/*
 * 
 */
package funcionario;

import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class Exer3FormCadastroFunconario extends javax.swing.JFrame {

    /**
     * Creates new form Exer3FormCadastroFunconario
     */
    public Exer3FormCadastroFunconario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtfNome = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        txtfCpf = new javax.swing.JTextField();
        lbEndereco = new javax.swing.JLabel();
        txtfEndereco = new javax.swing.JTextField();
        lbTelefone = new javax.swing.JLabel();
        txtfTelefone = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtfEmail = new javax.swing.JTextField();
        lbDataAdm = new javax.swing.JLabel();
        txtfDataAdm = new javax.swing.JTextField();
        lbCargo = new javax.swing.JLabel();
        txtfCargo = new javax.swing.JTextField();
        lbSalario = new javax.swing.JLabel();
        txtfSalario = new javax.swing.JTextField();
        lbDepartamento = new javax.swing.JLabel();
        txtfDepartamento = new javax.swing.JTextField();
        btnlimpar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        btngravar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNome.setText("Nome Completo");

        lbCpf.setText("Cpf");

        lbEndereco.setText("Endereço");

        lbTelefone.setText("Telefone");

        lbEmail.setText("Email");

        lbDataAdm.setText("Data de Admissão");

        txtfDataAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDataAdmActionPerformed(evt);
            }
        });

        lbCargo.setText("Cargo");

        lbSalario.setText("Salário");

        lbDepartamento.setText("Departamento");

        btnlimpar.setText("limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        btnmostrar.setText("mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        btngravar.setText("graxar");
        btngravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(lbCpf)
                    .addComponent(lbEndereco)
                    .addComponent(lbTelefone)
                    .addComponent(lbEmail)
                    .addComponent(lbDataAdm)
                    .addComponent(lbCargo)
                    .addComponent(lbSalario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btngravar)
                        .addComponent(lbDepartamento)))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfNome)
                    .addComponent(txtfCpf)
                    .addComponent(txtfEndereco)
                    .addComponent(txtfTelefone)
                    .addComponent(txtfEmail)
                    .addComponent(txtfDataAdm)
                    .addComponent(txtfCargo)
                    .addComponent(txtfSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtfDepartamento))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmostrar)
                .addGap(18, 18, 18)
                .addComponent(btnlimpar)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(txtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(txtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefone)
                    .addComponent(txtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbDataAdm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtfDataAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCargo)
                    .addComponent(txtfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSalario)
                    .addComponent(txtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartamento)
                    .addComponent(txtfDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpar)
                    .addComponent(btnmostrar)
                    .addComponent(btngravar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfDataAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDataAdmActionPerformed
   
    }//GEN-LAST:event_txtfDataAdmActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
       limpar();
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
       funcionario fu = this.montarfuncionario();
       JOptionPane.showMessageDialog(null,"NomeCompelrto: "+fu.getNomeCompelrto()+"\nCpf: "+fu.getCpf()+"\nEndereco: " +
       fu.getEndereco()+"\nEmail: "+fu.getEmail()+"\nDatadeAdmissao: "+fu.getDatadeAdmissao()+"\nCargo: "+fu.getCargo()+
       "\nSalario: "+fu.getSalario()+"\nDepartamento: "+fu.getDepartamento());
       
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btngravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngravarActionPerformed
        funcionario fu = this.montarfuncionario();
        funcionariocontrole fuc = new funcionariocontrole();
        fuc.insert(fu);
        
    }//GEN-LAST:event_btngravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exer3FormCadastroFunconario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exer3FormCadastroFunconario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exer3FormCadastroFunconario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exer3FormCadastroFunconario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exer3FormCadastroFunconario().setVisible(true);
            }
        });
    }
    public funcionario montarfuncionario(){
        funcionario fu = new funcionario();
        fu.setNomeCompelrto(txtfNome.getText());
        fu.setCpf(txtfCpf.getText());
        fu.setEndereco(txtfEndereco.getText());
        fu.setEmail(txtfEmail.getText());
        fu.setDatadeAdmissao(txtfDataAdm.getText());
        fu.setCargo(txtfCargo.getText());
        fu.setSalario(Float.parseFloat(txtfSalario.getText()));
        fu.setDepartamento(txtfDepartamento.getText());
        return fu;
    }
    
    public void limpar(){
        txtfNome.setText("");
        txtfCpf.setText("");
        txtfEndereco.setText("");
        txtfEmail.setText("");
        txtfDataAdm.setText("");
        txtfDepartamento.setText("");
        txtfCargo.setText("");
        txtfSalario.setText("");
        txtfDepartamento.setText("");
        
      
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngravar;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbDataAdm;
    private javax.swing.JLabel lbDepartamento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JTextField txtfCargo;
    private javax.swing.JTextField txtfCpf;
    private javax.swing.JTextField txtfDataAdm;
    private javax.swing.JTextField txtfDepartamento;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JTextField txtfEndereco;
    private javax.swing.JTextField txtfNome;
    private javax.swing.JTextField txtfSalario;
    private javax.swing.JTextField txtfTelefone;
    // End of variables declaration//GEN-END:variables
}
