/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orientaçãoobjetos;

/**
 *
 * @author Senac
 */
public class Exer8FormCContas extends javax.swing.JFrame {

    /**
     * Creates new form Exer8FormCContas
     */
    public Exer8FormCContas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDescricao = new javax.swing.JLabel();
        txtfDescricao = new javax.swing.JTextField();
        lbValor = new javax.swing.JLabel();
        txtfValor = new javax.swing.JTextField();
        lbDatavencinento = new javax.swing.JLabel();
        txtfDatavencimento = new javax.swing.JTextField();
        lbDatapagamento = new javax.swing.JLabel();
        txtfDatapagamento = new javax.swing.JTextField();
        lbFornecedor = new javax.swing.JLabel();
        txtfFornecedor = new javax.swing.JTextField();
        lbCategoria = new javax.swing.JLabel();
        txtfCategoria = new javax.swing.JTextField();
        lbEstatuspagamento = new javax.swing.JLabel();
        txtfEstatuspagamento = new javax.swing.JTextField();
        lbMetodopagamento = new javax.swing.JLabel();
        txtfMetodopagamento = new javax.swing.JTextField();
        lbObservacoes = new javax.swing.JLabel();
        txtfObservacoes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDescricao.setText("Descrição");
        jPanel1.add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, -1, -1));

        txtfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtfDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, -1));

        lbValor.setText("valor");
        jPanel1.add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(txtfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, -1));

        lbDatavencinento.setText("Data de vencimento");
        jPanel1.add(lbDatavencinento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtfDatavencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDatavencimentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtfDatavencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));

        lbDatapagamento.setText("Data de pagamento");
        jPanel1.add(lbDatapagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(txtfDatapagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, -1));

        lbFornecedor.setText("Fornecedor");
        jPanel1.add(lbFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(txtfFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, -1));

        lbCategoria.setText("Categoria");
        jPanel1.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(txtfCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 160, -1));

        lbEstatuspagamento.setText("Estatus de pagamento");
        jPanel1.add(lbEstatuspagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(txtfEstatuspagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 170, -1));

        lbMetodopagamento.setText("Metodo de pagamento");
        jPanel1.add(lbMetodopagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        jPanel1.add(txtfMetodopagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 160, -1));

        lbObservacoes.setText("Observações");
        jPanel1.add(lbObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        jPanel1.add(txtfObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDescricaoActionPerformed

    private void txtfDatavencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDatavencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDatavencimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exer8FormCContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exer8FormCContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exer8FormCContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exer8FormCContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exer8FormCContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbDatapagamento;
    private javax.swing.JLabel lbDatavencinento;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbEstatuspagamento;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbMetodopagamento;
    private javax.swing.JLabel lbObservacoes;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField txtfCategoria;
    private javax.swing.JTextField txtfDatapagamento;
    private javax.swing.JTextField txtfDatavencimento;
    private javax.swing.JTextField txtfDescricao;
    private javax.swing.JTextField txtfEstatuspagamento;
    private javax.swing.JTextField txtfFornecedor;
    private javax.swing.JTextField txtfMetodopagamento;
    private javax.swing.JTextField txtfObservacoes;
    private javax.swing.JTextField txtfValor;
    // End of variables declaration//GEN-END:variables
}
